#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Please wait styling, testing and building your work before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '😥 Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed type check. Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo 'Alright... Code looks great... Will the build succeed? 🤔'

npm run build ||
(
    echo '❌👷🔨 Project build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo '✅ Everything is good... Commiting code in a few 🚀✅'